package(default_visibility = ["//lib/bazel:__pkg__"])

filegroup(
    name = "tool-wrappers",
    srcs = [
        "ar",
        "as",
        "gcc",
        "ld",
        "nm",
        "objcopy",
        "objdump",
        "set_env",
        "strip",
        "//third_party_toolchains/arm_linux_gnueabi:compiler_components",
    ],
)
