# Copyright 2020 Makani Technologies LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Automatically generated crosswind controllers.

This file was generated by: analysis/control/generate_crosswind_controllers.m.
"""

from makani.control import control_types as m


def GetControllers(wing_serial):
  """Returns PID gains for crosswind airspeed controllers."""
  if wing_serial == m.kWingSerialOktoberKite01:
    airspeed = {
        'kp': 3.63e+03,
        'ki': 2.08e+03,
        'kd': 0.00
    }
  else:
    assert False, 'wing_serial %d was not recognized' % wing_serial

  return {
      'airspeed': airspeed,
  }
