package(default_visibility = ["//visibility:public"])

load("//lib/bazel:py_rules.bzl", "py_binary")

py_binary(
    name = "list",
    srcs = ["list.py"],
    deps = [
        "//gs/monitor2/apps/layout:webmonitor_layout",
    ],
)
